/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteImport } from './routes/_project'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as ProjectSuggestionsIndexRouteImport } from './routes/_project/suggestions/index'
import { Route as ProjectRoadmapIndexRouteImport } from './routes/_project/roadmap/index'

const ProjectRoute = ProjectRouteImport.update({
  id: '/_project',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSuggestionsIndexRoute = ProjectSuggestionsIndexRouteImport.update({
  id: '/suggestions/',
  path: '/suggestions/',
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectRoadmapIndexRoute = ProjectRoadmapIndexRouteImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => ProjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/roadmap/': typeof ProjectRoadmapIndexRoute
  '/suggestions/': typeof ProjectSuggestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/roadmap': typeof ProjectRoadmapIndexRoute
  '/suggestions': typeof ProjectSuggestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_project': typeof ProjectRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_project/roadmap/': typeof ProjectRoadmapIndexRoute
  '/_project/suggestions/': typeof ProjectSuggestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/roadmap/'
    | '/suggestions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/roadmap'
    | '/suggestions'
  id:
    | '__root__'
    | '/_marketing'
    | '/_project'
    | '/auth/_layout'
    | '/auth/login'
    | '/auth/signup'
    | '/_marketing/'
    | '/_project/roadmap/'
    | '/_project/suggestions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  ProjectRoute: typeof ProjectRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_project': {
      id: '/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project/suggestions/': {
      id: '/_project/suggestions/'
      path: '/suggestions'
      fullPath: '/suggestions/'
      preLoaderRoute: typeof ProjectSuggestionsIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/_project/roadmap/': {
      id: '/_project/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof ProjectRoadmapIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface ProjectRouteChildren {
  ProjectRoadmapIndexRoute: typeof ProjectRoadmapIndexRoute
  ProjectSuggestionsIndexRoute: typeof ProjectSuggestionsIndexRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectRoadmapIndexRoute: ProjectRoadmapIndexRoute,
  ProjectSuggestionsIndexRoute: ProjectSuggestionsIndexRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  ProjectRoute: ProjectRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
