/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as InternalRouteImport } from './routes/_internal'
import { Route as ExternalRouteImport } from './routes/_external'
import { Route as ExternalIndexRouteImport } from './routes/_external/index'
import { Route as InternalAccountRouteImport } from './routes/_internal/account'
import { Route as InternalProjectsIndexRouteImport } from './routes/_internal/projects/index'
import { Route as ExternalAuthVerifyEmailRouteImport } from './routes/_external/auth/verify-email'
import { Route as ExternalAuthSignupRouteImport } from './routes/_external/auth/signup'
import { Route as ExternalAuthLoginRouteImport } from './routes/_external/auth/login'
import { Route as ProjectProjectSlugSuggestionsIndexRouteImport } from './routes/project/$projectSlug/suggestions/index'
import { Route as ProjectProjectSlugRoadmapIndexRouteImport } from './routes/project/$projectSlug/roadmap/index'

const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRoute = InternalRouteImport.update({
  id: '/_internal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalRoute = ExternalRouteImport.update({
  id: '/_external',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalIndexRoute = ExternalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExternalRoute,
} as any)
const InternalAccountRoute = InternalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => InternalRoute,
} as any)
const InternalProjectsIndexRoute = InternalProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => InternalRoute,
} as any)
const ExternalAuthVerifyEmailRoute = ExternalAuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => ExternalRoute,
} as any)
const ExternalAuthSignupRoute = ExternalAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => ExternalRoute,
} as any)
const ExternalAuthLoginRoute = ExternalAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => ExternalRoute,
} as any)
const ProjectProjectSlugSuggestionsIndexRoute =
  ProjectProjectSlugSuggestionsIndexRouteImport.update({
    id: '/$projectSlug/suggestions/',
    path: '/$projectSlug/suggestions/',
    getParentRoute: () => ProjectRoute,
  } as any)
const ProjectProjectSlugRoadmapIndexRoute =
  ProjectProjectSlugRoadmapIndexRouteImport.update({
    id: '/$projectSlug/roadmap/',
    path: '/$projectSlug/roadmap/',
    getParentRoute: () => ProjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ExternalIndexRoute
  '/project': typeof ProjectRouteWithChildren
  '/account': typeof InternalAccountRoute
  '/auth/login': typeof ExternalAuthLoginRoute
  '/auth/signup': typeof ExternalAuthSignupRoute
  '/auth/verify-email': typeof ExternalAuthVerifyEmailRoute
  '/projects/': typeof InternalProjectsIndexRoute
  '/project/$projectSlug/roadmap/': typeof ProjectProjectSlugRoadmapIndexRoute
  '/project/$projectSlug/suggestions/': typeof ProjectProjectSlugSuggestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ExternalIndexRoute
  '/project': typeof ProjectRouteWithChildren
  '/account': typeof InternalAccountRoute
  '/auth/login': typeof ExternalAuthLoginRoute
  '/auth/signup': typeof ExternalAuthSignupRoute
  '/auth/verify-email': typeof ExternalAuthVerifyEmailRoute
  '/projects': typeof InternalProjectsIndexRoute
  '/project/$projectSlug/roadmap': typeof ProjectProjectSlugRoadmapIndexRoute
  '/project/$projectSlug/suggestions': typeof ProjectProjectSlugSuggestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_external': typeof ExternalRouteWithChildren
  '/_internal': typeof InternalRouteWithChildren
  '/project': typeof ProjectRouteWithChildren
  '/_internal/account': typeof InternalAccountRoute
  '/_external/': typeof ExternalIndexRoute
  '/_external/auth/login': typeof ExternalAuthLoginRoute
  '/_external/auth/signup': typeof ExternalAuthSignupRoute
  '/_external/auth/verify-email': typeof ExternalAuthVerifyEmailRoute
  '/_internal/projects/': typeof InternalProjectsIndexRoute
  '/project/$projectSlug/roadmap/': typeof ProjectProjectSlugRoadmapIndexRoute
  '/project/$projectSlug/suggestions/': typeof ProjectProjectSlugSuggestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project'
    | '/account'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/projects/'
    | '/project/$projectSlug/roadmap/'
    | '/project/$projectSlug/suggestions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/project'
    | '/account'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/projects'
    | '/project/$projectSlug/roadmap'
    | '/project/$projectSlug/suggestions'
  id:
    | '__root__'
    | '/_external'
    | '/_internal'
    | '/project'
    | '/_internal/account'
    | '/_external/'
    | '/_external/auth/login'
    | '/_external/auth/signup'
    | '/_external/auth/verify-email'
    | '/_internal/projects/'
    | '/project/$projectSlug/roadmap/'
    | '/project/$projectSlug/suggestions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExternalRoute: typeof ExternalRouteWithChildren
  InternalRoute: typeof InternalRouteWithChildren
  ProjectRoute: typeof ProjectRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal': {
      id: '/_internal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_external': {
      id: '/_external'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_external/': {
      id: '/_external/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ExternalIndexRouteImport
      parentRoute: typeof ExternalRoute
    }
    '/_internal/account': {
      id: '/_internal/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof InternalAccountRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/projects/': {
      id: '/_internal/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof InternalProjectsIndexRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_external/auth/verify-email': {
      id: '/_external/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof ExternalAuthVerifyEmailRouteImport
      parentRoute: typeof ExternalRoute
    }
    '/_external/auth/signup': {
      id: '/_external/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof ExternalAuthSignupRouteImport
      parentRoute: typeof ExternalRoute
    }
    '/_external/auth/login': {
      id: '/_external/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof ExternalAuthLoginRouteImport
      parentRoute: typeof ExternalRoute
    }
    '/project/$projectSlug/suggestions/': {
      id: '/project/$projectSlug/suggestions/'
      path: '/$projectSlug/suggestions'
      fullPath: '/project/$projectSlug/suggestions/'
      preLoaderRoute: typeof ProjectProjectSlugSuggestionsIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/project/$projectSlug/roadmap/': {
      id: '/project/$projectSlug/roadmap/'
      path: '/$projectSlug/roadmap'
      fullPath: '/project/$projectSlug/roadmap/'
      preLoaderRoute: typeof ProjectProjectSlugRoadmapIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
  }
}

interface ExternalRouteChildren {
  ExternalIndexRoute: typeof ExternalIndexRoute
  ExternalAuthLoginRoute: typeof ExternalAuthLoginRoute
  ExternalAuthSignupRoute: typeof ExternalAuthSignupRoute
  ExternalAuthVerifyEmailRoute: typeof ExternalAuthVerifyEmailRoute
}

const ExternalRouteChildren: ExternalRouteChildren = {
  ExternalIndexRoute: ExternalIndexRoute,
  ExternalAuthLoginRoute: ExternalAuthLoginRoute,
  ExternalAuthSignupRoute: ExternalAuthSignupRoute,
  ExternalAuthVerifyEmailRoute: ExternalAuthVerifyEmailRoute,
}

const ExternalRouteWithChildren = ExternalRoute._addFileChildren(
  ExternalRouteChildren,
)

interface InternalRouteChildren {
  InternalAccountRoute: typeof InternalAccountRoute
  InternalProjectsIndexRoute: typeof InternalProjectsIndexRoute
}

const InternalRouteChildren: InternalRouteChildren = {
  InternalAccountRoute: InternalAccountRoute,
  InternalProjectsIndexRoute: InternalProjectsIndexRoute,
}

const InternalRouteWithChildren = InternalRoute._addFileChildren(
  InternalRouteChildren,
)

interface ProjectRouteChildren {
  ProjectProjectSlugRoadmapIndexRoute: typeof ProjectProjectSlugRoadmapIndexRoute
  ProjectProjectSlugSuggestionsIndexRoute: typeof ProjectProjectSlugSuggestionsIndexRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectProjectSlugRoadmapIndexRoute: ProjectProjectSlugRoadmapIndexRoute,
  ProjectProjectSlugSuggestionsIndexRoute:
    ProjectProjectSlugSuggestionsIndexRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ExternalRoute: ExternalRouteWithChildren,
  InternalRoute: InternalRouteWithChildren,
  ProjectRoute: ProjectRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
