export const MEMBER_ROLES = ['USER', 'ADMIN'];
export const SUGGESTION_CATEGORIES = ['FEATURE', 'BUG'];
export const SUGGESTION_STATUSES = ['OPEN', 'PLANNED', 'IN_PROGRESS', 'DONE', 'REJECTED'];
export const NOTIFICATION_TYPES = [
    'SUGGESTION_CREATED',
    'SUGGESTION_REJECTED',
    'SUGGESTION_COMMENT',
    'SUGGESTION_PLANNED',
    'SUGGESTION_STATUS_CHANGED',
];
